import { useRef, useState } from 'react';
import { Link } from 'react-router';
import { applications, filterApplications, type Application } from '../applicationData';
import { Mark } from '../components/Mark';

export function PortalPage() {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'all' | 'review' | 'waiting'>('all');
  const [selected, setSelected] = useState<Application | null>(null);
  const dialog = useRef<HTMLDialogElement>(null);
  const shown = filterApplications(applications, query, filter);
  const today = new Intl.DateTimeFormat('en-IE', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date()).toUpperCase();
  const openCase = (row: Application) => { setSelected(row); dialog.current?.showModal(); };
  return <div className="portal-page">
    <header className="portal-header"><div className="portal-header-inner"><Link to="/" aria-label="Agentic Lender home"><Mark /></Link><nav aria-label="Portal navigation"><span aria-current="page">My work</span><span>Applications</span><span>Team</span></nav><span className="portal-person"><b>NK</b> Nikoloz</span></div></header>
    <main className="portal-main"><div className="portal-welcome"><div><p className="eyebrow"><span className="eyebrow-line" /> {today}</p><h1>Good morning, Nikoloz.</h1><p>Review submitted documents and follow up on missing information.</p></div><Link to="/" className="portal-home-link">View the story ↗</Link></div>
      <div className="portal-summary"><strong>3</strong><span>applications assigned to you · <b>1</b> needs documents before review can continue</span></div>
      <div className="portal-section-head"><div><h2>Your next steps</h2><p>Start with the files ready for attention.</p></div><span>FICTIONAL RECORDS / PREVIEW</span></div>
      <div className="portal-controls"><label className="portal-search"><span className="sr-only">Search by borrower or application reference</span><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" stroke="currentColor" strokeWidth="1.7"/><path d="m15.5 15.5 5 5" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round"/></svg><input type="search" placeholder="Find a name or application…" value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="portal-filters" role="group" aria-label="Filter applications"><button className={filter === 'all' ? 'active' : ''} aria-pressed={filter === 'all'} onClick={() => setFilter('all')}>All · 3</button><button className={filter === 'review' ? 'active' : ''} aria-pressed={filter === 'review'} onClick={() => setFilter('review')}>For review · 2</button><button className={filter === 'waiting' ? 'active' : ''} aria-pressed={filter === 'waiting'} onClick={() => setFilter('waiting')}>Waiting · 1</button></div></div>
      <div className="portal-list" aria-live="polite">{shown.map((row) => <button type="button" className="portal-row" key={row.id} onClick={() => openCase(row)}><span className="portal-borrower"><span className="portal-avatar">{row.name.split(' ').map((part) => part[0]).join('')}</span><span><strong>{row.name}</strong><small>{row.id} · {row.type}</small></span></span><span className="portal-amount"><strong>{row.amount}</strong><small>Requested loan</small></span><span className="portal-due">{row.due}</span><span className={`portal-status ${row.status === 'Needs documents' ? 'status-waiting' : ''}`}>{row.status}</span><span className="portal-row-arrow" aria-hidden="true">↗</span></button>)}{shown.length === 0 && <div className="portal-empty"><strong>No matching applications</strong><p>Try another name or clear the filters.</p><button onClick={() => { setQuery(''); setFilter('all'); }}>Clear search and filters</button></div>}</div>
      <p className="portal-footnote">Prototype preview · Sample names and amounts · No borrower data or decisions are stored</p>
    </main>
    <dialog className="case-dialog" ref={dialog} onClose={() => setSelected(null)} aria-labelledby="case-dialog-title"><form method="dialog" className="case-dialog-top"><span>{selected?.id} / APPLICATION</span><button aria-label="Close application details" type="submit">×</button></form><h2 id="case-dialog-title">{selected?.name}</h2><p>{selected?.type}</p><span className={`portal-status ${selected?.status === 'Needs documents' ? 'status-waiting' : ''}`}>{selected?.status}</span><dl className="case-facts"><div><dt>Requested loan</dt><dd>{selected?.amount}</dd></div><div><dt>Review stage</dt><dd>{selected?.status === 'Needs documents' ? 'Documents' : 'Review'}</dd></div></dl><h3>Document checklist</h3><ul><li><span>Photo identification</span><strong>Received</strong></li><li><span>Bank statements</span><strong>Received</strong></li><li><span>Latest payslip</span><strong className={selected?.status === 'Needs documents' ? 'needed' : ''}>{selected?.status === 'Needs documents' ? 'Needed' : 'Received'}</strong></li></ul><div className="case-next"><small>NEXT ACTION</small><h3>{selected?.status === 'Needs documents' ? 'Follow up on the payslip' : 'Continue the loan review'}</h3><p>{selected?.status === 'Needs documents' ? 'The latest payslip is outstanding. Your broker can request it before the review continues.' : 'Review the documents, income breakdown, and property valuation before recording a decision.'}</p></div><p className="case-prototype-note">This is a design preview. No message is sent and no decision is recorded.</p></dialog>
  </div>;
}
